title: W2GenAI Lab
description: Advancing the Frontiers of Generative AI Research
url: "https://w2genai-lab.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Include directories
include:
  - _pages
  - LucidFlux

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - Gemfiles
  - CLAUDE.md
  - run_cc.sh

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "LucidFlux"
    values:
      layout: "default"